@startuml start_new_game_sequence_diagram

Server -> Client1: send "game-end" + remaining time to 0.0s
Server -> Client2: send "game-end" + remaining time to 0.0s
Server -> Client3: send "game-end" + remaining time to 0.0s
Server -> Client4: send "game-end" + remaining time to 0.0s
Server -> Client5: send "game-end" + remaining time to 0.0s
Server -> Spectator: send "game-end" + remaining time to 0.0s
Client1 -> Server: send "player-ready"
Server -> Client1: send "game-init"
Client2 -> Server: send "player-ready"
Server -> Client2: send "game-init"
Client3 -> Server: send "player-ready"
Server -> Client3: send "game-init"
Client4 -> Server: send "player-ready"
Server -> Client4: send "game-init"
Client5 -> Server: send "player-ready"
Server -> Client5: send "game-init"

@enduml